
ATTACK = 'attack'
DEFENSE = 'defense'
COST = 'cost'
MOVEMENT = 'movement'

INFANTRY = 'infantry'
ARTILLERY = 'artillery'
MECHANIZED_INFANTRY = 'mechanized_infantry'
TANK = 'tank'
FIGHTER = 'fighter'
TACTICAL_BOMBER = 'tactical_bomber'
STRATEGIC_BOMBER = 'strategic_bomber'
AIRCRAFT_CARRIER = 'aircraft_carrier'
BATTLESHIP = 'battleship'
DESTROYER = 'destroyer'
CRUISER = 'cruiser'
SUBMARINE = 'submarine'
TRANSPORT = 'transport'

UNIT_INFO = {
    INFANTRY: {ATTACK: 1, DEFENSE: 2, COST: 3, MOVEMENT: 1},
    ARTILLERY: {ATTACK: 2, DEFENSE: 2, COST: 4, MOVEMENT: 2},
    MECHANIZED_INFANTRY: {ATTACK: 1, DEFENSE: 2, COST: 4, MOVEMENT: 2},
    TANK: {ATTACK: 3, DEFENSE: 3, COST: 6, MOVEMENT: 2},
    FIGHTER: {ATTACK: 3, DEFENSE: 4, COST: 10, MOVEMENT: 4},
    TACTICAL_BOMBER: {ATTACK: 3, DEFENSE: 3, COST: 11, MOVEMENT: 4},
    STRATEGIC_BOMBER: {ATTACK: 4, DEFENSE: 1, COST: 12, MOVEMENT: 6},
    AIRCRAFT_CARRIER: {ATTACK: 0, DEFENSE: 2, COST: 16, MOVEMENT: 2},
    BATTLESHIP: {ATTACK: 4, DEFENSE: 4, COST: 20, MOVEMENT: 2},
    DESTROYER: {ATTACK: 2, DEFENSE: 2, COST: 8, MOVEMENT: 2},
    CRUISER: {ATTACK: 3, DEFENSE: 3, COST: 12, MOVEMENT: 2},
    SUBMARINE: {ATTACK: 2, DEFENSE: 1, COST: 6, MOVEMENT: 2}
}

UNIT_NAMES = (
    INFANTRY,
    ARTILLERY,
    MECHANIZED_INFANTRY,
    TANK,
    FIGHTER,
    TACTICAL_BOMBER,
    STRATEGIC_BOMBER,
    AIRCRAFT_CARRIER,
    BATTLESHIP,
    DESTROYER,
    CRUISER,
    SUBMARINE,
    TRANSPORT
)
